# SD.Next Dockerfile
# docs: <https://github.com/vladmandic/sdnext/wiki/Docker>

# base image
FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

# metadata
LABEL org.opencontainers.image.vendor="SD.Next"
LABEL org.opencontainers.image.authors="vladmandic"
LABEL org.opencontainers.image.url="https://github.com/vladmandic/sdnext/"
LABEL org.opencontainers.image.documentation="https://github.com/vladmandic/sdnext/wiki/Docker"
LABEL org.opencontainers.image.source="https://github.com/vladmandic/sdnext/"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.title="SD.Next"
LABEL org.opencontainers.image.description="SD.Next: Advanced Implementation of Stable Diffusion and other Diffusion-based generative image models"
LABEL org.opencontainers.image.base.name="https://hub.docker.com/pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime"
LABEL org.opencontainers.image.version="latest"


# minimum install
RUN apt-get -y update && \
  apt-get -y --no-install-recommends install git build-essential google-perftools curl ffmpeg && \
  /usr/sbin/ldconfig

# optional if full cuda-dev is required by some downstream library
# RUN ["apt-get", "-y", "nvidia-cuda-toolkit"]

ARG NO_CACHE=true

# fix rich logs in container
ENV COLUMNS=200 
ENV LOG_STDOUT=true

# stop pip and uv from caching
ENV PIP_NO_CACHE_DIR=$NO_CACHE
ENV UV_NO_CACHE=$NO_CACHE
ENV PIP_ROOT_USER_ACTION=ignore
# disable model hashing for faster startup
ENV SD_NOHASHING=true
# set data directories
ENV SD_DATADIR="/mnt/data"
ENV SD_MODELSDIR="/mnt/models"
ENV SD_DOCKER=true

# tcmalloc is not required but it is highly recommended
ENV LD_PRELOAD=libtcmalloc.so.4

# import uv per https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
# compile bytecode, and use container venv
ENV UV_COMPILE_BYTECODE=1 \
    VIRTUAL_ENV=/opt/conda \
    PATH="/opt/conda/bin:$PATH"

# default runtime environment variables
ENV ACCELERATE=True \
    ATTN_PRECISION=fp16 \
    CUDA_AUTO_BOOST=1 \
    CUDA_CACHE_DISABLE=0 \
    CUDA_DEVICE_DEFAULT_PERSISTING_L2_CACHE_PERCENTAGE_LIMIT=0 \
    CUDA_LAUNCH_BLOCKING=0 \
    CUDA_MODULE_LOADING=LAZY \
    TORCH_CUDNN_V8_API_ENABLED=1 \
    FORCE_CUDA=1 \
    GRADIO_ANALYTICS_ENABLED=False \
    HF_HUB_DISABLE_EXPERIMENTAL_WARNING=1 \
    HF_HUB_DISABLE_TELEMETRY=1 \
    K_DIFFUSION_USE_COMPILE=0 \
    NUMEXPR_MAX_THREADS=16 \
    PYTHONHTTPSVERIFY=0 \
    SAFETENSORS_FAST_GPU=1 \
    TF_CPP_MIN_LOG_LEVEL=2 \
    TF_ENABLE_ONEDNN_OPTS=0 \
    USE_TORCH=1 \
    TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD=1 \
    UVICORN_TIMEOUT_KEEP_ALIVE=60 \
    KINETO_LOG_LEVEL=3 \
    DO_NOT_TRACK=1
  
# install deps
COPY uv.lock uv.lock
COPY pyproject.toml pyproject.toml
RUN uv sync --active --locked --no-install-project

#WIP for local build caching, mounting /opt/conda to local fs for now though
# COPY installer.py .
# COPY requirements.txt .
# COPY modules/rocm.py modules/rocm.py
# COPY otel/requirements.txt otel/requirements.txt
# # COPY launch.py .
# # COPY modules/cmd_args.py modules/cmd_args.py
# # COPY modules/rocm.py modules/rocm.py
# # COPY modules/script_loading.py modules/script_loading.py
# # COPY modules/zluda_installer.py modules/zluda_installer.py
# # COPY modules/paths.py modules/paths.py
# # COPY modules/timer.py modules/timer.py
# # COPY modules/errors.py modules/errors.py
# # COPY extensions/. ./extensions/
# # COPY extensions-builtin/. ./extensions-builtin/
# RUN python installer.py

# copy sdnext
COPY . /app
RUN uv sync --active --locked
# sdnext will run all necessary pip install ops and then exit
# RUN ["python", "/app/launch.py", "--debug", "--uv", "--api-only", "--use-cuda", "--log-stdout", "--test", "--optional"]
# preinstall additional packages to avoid installation during runtime

# COPY . /app
# actually run sdnext
# CMD python launch.py --debug --extensions-only --listen --api-log --log-stdout --api-only --docs
CMD python webui.py --listen --docs

# expose port
EXPOSE 7860

# healthcheck function
# HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=3 CMD curl --fail http://localhost:7860/sdapi/v1/status || exit 1

# stop signal
STOPSIGNAL SIGINT
